site_name: "msmu"
site_description: "Proteomics Analysis Toolkit based on MuData"
site_dir: "docs"

docs_dir: "mkdocs"

repo_name: "msmu"
repo_url: https://github.com/bertis-informatics/msmu

theme:
  name: "material"
  features:
    # - toc.integrate
    - navigation.tracking.off
    # - navigation.expand
    # - navigation.sections
    - content.tabs.link
    - content.code.copy
    - navigation.path
    - navigation.instant
    - navigation.indexes
  palette:
    - scheme: default
      primary: indigo # 라이트 모드 색상
      accent: indigo
      toggle:
        icon: material/weather-night
        name: "dark mode"
    - scheme: slate
      primary: indigo # 다크 모드 색상
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: "light mode"
  icon:
    repo: fontawesome/brands/github
  nav:
    hide_icons: false
  logo: "assets/favicon.svg"
  favicon: "assets/favicon.svg"

plugins:
  - gen-files:
      scripts:
        - "scripts/gen_ref_pages.py"
  - mkdocs-jupyter:
      execute: false # 이미 실행된 노트북만 렌더링할 때
      include_source: true # 소스 코드 셀 표시
      kernel_name: python3
      theme: dark
      ignore_h1_titles: true # 맨 위 h1 중복 방지
  - awesome-pages
  - literate-nav:
      nav_file: "nav.md"
  # - section-index
  - mkdocstrings:
      handlers:
        python:
          # ✅ 루트에 msmu/ 이므로 현재 디렉토리를 경로로
          paths: ["."]
          options:
            show_source: false
            separate_signature: true
            docstring_style: google
            merge_init_into_class: true
            show_if_no_docstring: false
            # 필요 시 프라이빗 제외
            filters: ["!^_"]
  - search
  - minify
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - toc:
      separator: "_"
  - admonition
  - footnotes
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - assets/custom.css

watch:
  - "mkdocs/"
  - "scripts/"
  - "msmu/"
