site_name: "msmu"
site_description: "Proteomics Analysis Toolkit based on MuData"
site_dir: "docs"

repo_name: "msmu"
repo_url: https://bitbucket.org/bertis/msmu

nav:
  # - "INTRODUCTION": "index.md"
  - "INSTALLATION": "installation.md"
  - "TUTORIALS":
      - "Quick Start": "tutorials/quick_start.ipynb"
      - "TMT": "tutorials/tmt.md"
      - "LFQ": "tutorials/lfq.md"
      - "DIA": "tutorials/dia.md"
      - "Visualization": "tutorials/visualization.md"
  - "API": "reference/" # From gen-files plugin

docs_dir: "mkdocs"

theme:
  name: material
  features:
    # - toc.integrate
    - navigation.tracking.off
    # - navigation.expand
    # - navigation.sections
    # - content.action.edit     # 페이지 우상단 "Edit this page" 버튼
    # - content.action.view     # (선택) "View source" 버튼
  palette:
    - scheme: default
      primary: indigo # 라이트 모드 색상
      accent: indigo
      toggle:
        icon: material/weather-night
        name: "dark mode"
    - scheme: slate
      primary: indigo # 다크 모드 색상
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: "light mode"
  icon:
    repo: fontawesome/brands/bitbucket
  nav:
    hide_icons: false

plugins:
  - gen-files:
      scripts:
        - "scripts/gen_ref_pages.py"
  - mkdocs-jupyter:
      execute: false # 이미 실행된 노트북만 렌더링할 때
      include_source: true # 소스 코드 셀 표시
      kernel_name: python3
      theme: dark
      ignore_h1_titles: true # 맨 위 h1 중복 방지
  - awesome-pages
  - literate-nav
  # - section-index
  - mkdocstrings:
      handlers:
        python:
          # ✅ 루트에 msmu/ 이므로 현재 디렉토리를 경로로
          paths: ["."]
          options:
            show_source: false
            separate_signature: true
            docstring_style: google
            merge_init_into_class: true
            show_if_no_docstring: false
            # 필요 시 프라이빗 제외
            # filters: ["!^_"]
  - search
  - minify
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.emoji
  - pymdownx.tasklist

extra_css:
  - assets/extra.css
  - assets/emoji.css
  - assets/jupyter-tweaks.css
